import { RenderContext } from "@/lib/products/types";

const styles = `
<style>
@page { size: A4; margin: 18mm 16mm; }
body{font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;background:#f7f8fa;color:#0f172a;margin:0}
.page{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:22px;min-height:255mm;margin:0 0 14px 0;page-break-after:always;position:relative}
.page:last-child{page-break-after:auto}.cover{background:linear-gradient(145deg,#ecfeff,#f8fafc)}h1{font-size:30px;margin:0 0 8px}h2{font-size:20px;margin:0 0 10px}h3{font-size:15px;margin:0 0 8px}p,li{font-size:12px;line-height:1.6;color:#334155}
.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px}.callout{border-left:4px solid #14b8a6;background:#f0fdfa;border-radius:10px;padding:10px 12px;margin:12px 0}
.table{width:100%;border-collapse:collapse}.table th{background:#f1f5f9;padding:8px;font-size:11px;text-align:left}.table td{padding:8px;border-bottom:1px solid #e2e8f0;font-size:11px}.table tr:nth-child(even) td{background:#f8fafc}.num{text-align:right}
.footer{position:absolute;bottom:10px;left:22px;right:22px;border-top:1px solid #e2e8f0;padding-top:6px;font-size:10px;color:#64748b;display:flex;justify-content:space-between}
</style>`;

function page(content: string, num: number) {
  return `<section class="page">${content}<div class="footer"><span>Generated by AvgPay • ${new Date().toLocaleDateString()} • Confidential</span><span>Page ${num}</span></div></section>`;
}

function cover(title: string, subtitle: string, ctx: RenderContext) {
  return `<section class="page cover"><h1>${title}</h1><p>${subtitle}</p><div class="meta"><div class="card"><strong>Job</strong><p>${ctx.jobLabel}</p></div><div class="card"><strong>City</strong><p>${ctx.cityLabel}</p></div><div class="card"><strong>Generated</strong><p>${ctx.generatedDate}</p></div><div class="card"><strong>Sample Size</strong><p>${ctx.stats.sampleSize}</p></div></div><div class="footer"><span>Generated by AvgPay • ${new Date().toLocaleDateString()} • Confidential</span><span>Page 1</span></div></section>`;
}

export function benchmarkHtml(ctx: RenderContext) {
  const sections = Array.from({ length: 19 }, (_, i) => `Benchmark Section ${i + 1}`);
  const body = sections.map((name, i) => page(`<h2>${name}</h2><p>This consulting-grade section interprets market ranges for ${ctx.jobLabel} in ${ctx.cityLabel}. Sample/Illustrative where noted.</p><div class="callout"><strong>Recommended Action:</strong> Anchor at $${ctx.anchor.toLocaleString()} and negotiate in $${ctx.askLow.toLocaleString()}-$${ctx.askHigh.toLocaleString()} range.</div><table class="table"><thead><tr><th>Percentile</th><th class="num">Total Comp</th></tr></thead><tbody><tr><td>P25</td><td class="num">$${ctx.stats.p25.toLocaleString()}</td></tr><tr><td>P50</td><td class="num">$${ctx.stats.p50.toLocaleString()}</td></tr><tr><td>P75</td><td class="num">$${ctx.stats.p75.toLocaleString()}</td></tr><tr><td>P90</td><td class="num">$${ctx.stats.p90.toLocaleString()}</td></tr></tbody></table>`, i + 2)).join("");
  return `<!doctype html><html><head><meta charset="utf-8"/>${styles}</head><body>${cover("Compensation Benchmark Report", "Consulting-grade benchmark for your job + city.", ctx)}${body}</body></html>`;
}

export function negotiationKitHtml(ctx: RenderContext) {
  const sections = Array.from({ length: 14 }, (_, i) => `Negotiation Playbook ${i + 1}`);
  const body = sections.map((name, i) => page(`<h2>${name}</h2><p>Use these scripts with confidence and clarity. Tie your ask to scope and impact.</p><div class="callout"><strong>Key Takeaway:</strong> Ask range $${ctx.askLow.toLocaleString()}-$${ctx.askHigh.toLocaleString()}, anchor $${ctx.anchor.toLocaleString()}, walk-away $${ctx.walkAway.toLocaleString()}.</div><h3>Script block</h3><ul><li>I'm excited to join and discuss compensation alignment.</li><li>Given role scope, I am targeting $${ctx.askHigh.toLocaleString()} total comp.</li><li>If we align on package structure, I can sign quickly.</li></ul>`, i + 2)).join("");
  return `<!doctype html><html><head><meta charset="utf-8"/>${styles}</head><body>${cover("Salary Negotiation Kit", "Know exactly what to ask for and how to say it.", ctx)}${body}</body></html>`;
}

export function negotiationChecklistHtml(ctx: RenderContext) {
  return `<!doctype html><html><head><meta charset="utf-8"/>${styles}</head><body>${cover("Negotiation Checklist", "Execution checklist for offer conversations.", ctx)}${page(`<h2>Checklist</h2><ul><li>Set floor, target, stretch.</li><li>Document proof of impact.</li><li>Prepare opening + anchor + close scripts.</li><li>Send recap within 2 hours.</li></ul><div class="callout"><strong>Recommended Action:</strong> Keep your ask in the ${ctx.askLow.toLocaleString()}-${ctx.askHigh.toLocaleString()} band.</div>`, 2)}</body></html>`;
}

export function blueprintHtml(ctx: RenderContext) {
  const sections = Array.from({ length: 14 }, (_, i) => `Blueprint Section ${i + 1}`);
  const body = sections.map((name, i) => page(`<h2>${name}</h2><p>Roadmap for comp progression over the next 12 months.</p><table class="table"><thead><tr><th>Skill</th><th class="num">ROI Premium</th></tr></thead><tbody>${ctx.skillPremiums.slice(0, 6).map((s) => `<tr><td>${s.skill}</td><td class="num">+${s.premium}%</td></tr>`).join("")}</tbody></table><div class="callout"><strong>Recommended Action:</strong> Ship proof-of-work every month and calibrate to ${ctx.askHigh.toLocaleString()} target.</div>`, i + 2)).join("");
  return `<!doctype html><html><head><meta charset="utf-8"/>${styles}</head><body>${cover("Career Path Pay Blueprint", "Your next 12 months mapped to a higher salary.", ctx)}${body}</body></html>`;
}
